name: Publish Nuget Package
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version Number'
        required: true
        type: string
jobs:
  Publish-Nuget:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: cd Nick.HtmlParser;dotnet build --no-restore -p:Version=${{ github.event.inputs.version }} --configuration Release;cd ..;
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet pack -c Release --version-suffix ${{ github.event.inputs.version }}
    - name: Push to Nuget
      run: dotnet nuget push ./Nick.HtmlParser/bin/Release/Nick.HtmlParser.${{ github.event.inputs.version }}.nupkg --api-key ${{ secrets.NUGETAPIKEY }} -s https://api.nuget.org/v3/index.json
    - name: Create Github Release
      run: gh release create ${{ github.event.inputs.version }} --generate-notes
    - name: Clean
      run: dotnet clean
