name: Publish Nuget Package
on:
  push:
    tags:
      - '*'
jobs:
  Publish-Nuget:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -p:Version={{ git describe --abbrev=0 }} --configuration Release
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet pack -c Release --version-suffix {{ git describe --abbrev=0 }}
    - name: Push to Nuget
      run: dotnet nuget push ./Nick.HtmlParser/bin/Release/Nick.HtmlParser.{{ git describe --abbrev=0 }}.nupkg --api-key ${{ secrets.NUGETAPIKEY }} -s https://api.nuget.org/v3/index.json
    - name: Create Github Release
      run: gh release create {{ git describe --abbrev=0 }} --generate-notes
    - name: Clean
      run: dotnet clean
